### ISSUE TITLE
transformation for plots

### ISSUE THREAD

**Issue by ajcardenasb** [FrederickHuangLin/ANCOMBC#10]
Dear Huang,

Thanks for providing your continuous support to ANCOM and ANCOM-BC users!

I'm wondering what is the best way to plot changes in abundances of DA features identified with ANCOM-BC. I used to plot clr-transformed counts on heatmaps when I was using ANCOM but now that I switched to ANCOM-BC I get very conflicting results regarding more or less abundant features in two conditions in comparison with ANCOM-BC results. For instance, ANCOM-BC identifies featureX as differentially more abundant in treatmentA vs treatmentB but when I plot the clr-transformed abundances I get the opposite pattern. This only happens for some features, the majority of them are consistent with ANCOMBC results, but sometimes I need to focus on those exceptions and haven't found a better way to plot them. 

Any help is appreciated!

Thanks,
Anny

**Comment by FrederickHuangLin** [comment]
Hi Anny,

Thanks for your interest in ANCOM and ANCOMBC! Please kindly find below my responses:

> I'm wondering what is the best way to plot changes in abundances of DA features identified with ANCOM-BC.

As for the primary analysis, visualizations using either `beta` values (unstandardized effect size) or `W` statistics (standardized effect size) would be a good way to show changes in absolute abundances. A positive value indicates an increase in absolute abundances as compared to the reference level; a negative value, on the other hand, indicates a decrease in absolute abundances. This [vignette](https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html#ancombc-global-test-result) shows an example of using waterfall plots.

> I used to plot clr-transformed counts on heatmaps when I was using ANCOM but now that I switched to ANCOM-BC I get very conflicting results.

Indeed, it happens sometimes that the clr-transformed values and ANCOMBC `W` statistics give a contradictory answer, which is basically because clr transformation relies on the geometric mean of observed abundances as a reference. For example, if taxon X is more abundant in treatment A than treatment B; however, if the geometric mean in treatment A is even larger than that of treatment B, the clr-transformed values of taxon X will show an opposite direction. I would recommend using `W` statistics as the input values for your heatmap so the interpretations will be more consistent.

Hope it helps :)
Huang

**Comment by ajcardenasb** [comment]
Thank Huang! 
Very helpful and makes complete sense. 
All the best,
Anny
