### ISSUE TITLE
Help understanding outputs

### ISSUE THREAD

**Issue by rowan-thomas** [FrederickHuangLin/ANCOMBC#100]
Hi,

Thank you so much for developing this package! It looks really helpful for the analysis that I'm doing. 

I'm a little confused about how to understand the outputs that ancombc gives. From my understanding, previous versions gave w-statistics that were only positive and with a larger range. Would you be able to explain what the w-statistic means in this version and how to use it for determining taxa that are more significant than others? Thank you!

**Comment by FrederickHuangLin** [comment]
Hi @rowan-thomas,

As for your questions

> From my understanding, previous versions gave w-statistics that were only positive and with a larger range. 

When you said the "previous version",  do you mean ANCOM? ANCOM and ANCOM-BC are two different methodologies and have different definitions of test statistics (W statistics). For ANCOM,  W statistics are essentially the number of significant pairwise comparisons, so it ranges from 0 to the number of taxa in your data. On the other hand, W statistics in ANCOM-BC are the standardized effect sizes so that they can be positive, negative, or zeros.

> how to use it for determining taxa that are more significant than others

p-values and adjusted p-values are provided in ANCOM-BC outputs, which can be used to quantify the significance across taxa somehow.

Best,
Huang
