### ISSUE TITLE
Structural zeros, filters, differences between ANCOM and ANCOM-BC

### ISSUE THREAD

**Issue by sunsvet** [FrederickHuangLin/ANCOMBC#102]
Hello Frederick, 

Thanks again for this package and your hard work on improving it continuously. It has been essential for my PhD!
I saw that you have just submitted an update, so looking forward to it! I have a few questions below. Here is a little context of my research design. 
I am currently running an analysis on a dataset (N=97) with shotgun metagenomics data which includes 317 species (after filtering <10 non-zero counts and <100 reads in at least 1 sample). I have 4 groups, which I am using for 3 main comparisons. For the purpose of simplifying the design, I will number them. The idea here is that the patients are subgrouped. 
**1.** 1 (healthy) vs 2 (patients) (N=25 & N=72)
**2.** 2.1 vs 2.2 (N=24 & N=48)
**3.** 2.2.1 vs 2.2.2 (N= 26 & N=22)

**1) How do you decide what filters to use in ANCOM-BC and ANCOM?** 
I read [this](https://github.com/FrederickHuangLin/ANCOMBC/issues/82) however I am still unsure which limits to use considering my sample sizes vary quite a lot for every group. 
For example for comparison **1** with:
 ```struc_zero = TRUE, neg_lb = TRUE```  I get 88 significant species
```struc_zero = FALSE, neg_lb = FALSE``` I get 19 and 
```struc_zero = TRUE, neg_lb = FALSE``` I get 19. 
One thing I still don't understand is why are structural zeros a problem? Let's say we have 2 groups, and one them has Taxon A in 15 samples, and one of them has Taxon A in 0 samples, isn't this a strong indicator that there are differences between these groups for Taxon A?
**2. Why are there different results depending on whether you do ANCOM-BC or ANCOM?** 
For the same group comparison as mentioned above I get:
 ```struc_zero = TRUE, neg_lb = TRUE```  I get 70 significant species (attached for reference) [profiles_counts_trs_rm0_317_nc_scz_TT.tsv.ancom.txt](https://github.com/FrederickHuangLin/ANCOMBC/files/9753140/profiles_counts_trs_rm0_317_nc_scz_TT.tsv.ancom.txt)
```struc_zero = FALSE, neg_lb = FALSE``` I get 0 
[profiles_counts_trs_rm0_317_nc_scz_FF.tsv.ancom.txt](https://github.com/FrederickHuangLin/ANCOMBC/files/9753154/profiles_counts_trs_rm0_317_nc_scz_FF.tsv.ancom.txt)
```struc_zero = TRUE, neg_lb = FALSE``` I get 4 and their W stats are still Inf (structural zeros again).
**3. If all the significant differences come up with a W=Inf, would you exclude these results?**
**4. How can you create a volcano plot for findings with W=Inf?**
 When I try to use the code in the ANOM-BC manual to visualise the W statistic for ANCOM, it doesn't work due to the missing W-stats values. 
**5. What does an SE=0 mean if ANCOM-BC considers taxon to be significantly abundant practically?**
A lot of the species that are considered to be significantly different in my analysis have an SE=0 and are significantly abundant so I am not sure what to make of this. 
![waterfall plot](https://user-images.githubusercontent.com/100886701/195046444-b16be628-a3ea-41d0-a4e2-05a76a2c2834.png)
**6. Can you access clr mean differences in ANCOM-BC and the updated ANCOM?**
In the old version of ANCOM, you could obtain a volcano plot with clr mean differences. I found it was sometimes more useful than log-fold change. Is there a way to access this still?
**7. In general should I worry of I have many 0s for W-statistics (e.g. 206/300)?**
Does this mean that my sample is not large enough? Should I then be using higher level taxonomy.  

Apologies for the long post, I have been trying to figure out the answers to these questions for a few months now, and have been a bit stuck. I hope it makes sense.
Thank you so so much for what you do!

**Comment by FrederickHuangLin** [comment]
Hi @sunsvet,

Thanks for your questions!

I am aware that many people are confused about the definition of structural zeros, so the following clarifications have been added to the new ANCOMBC release

> A taxon is considered to have structural zeros in some (>=1) groups if it is completely (or nearly completely) missing in these groups. For instance, suppose there are three groups: g1, g2, and g3. If the counts of taxon A in g1 are 0, but they are nonzero in g2 and g3, then taxon A will be considered to contain structural zeros in g1. In this example, taxon A is declared to be differentially abundant between g1 and g2, g1 and g3, and consequently, it is globally differentially abundant with respect to this group variable. Such taxa are not further analyzed using ANCOM-BC2, but the results are summarized in the overall summary.

Basically, we recommend separate discussions on taxa with structural zeros (NOT detected by ANCOM, ANCOM-BC, or ANCOM-BC2) and taxa without structural zeros (detected by ANCOM, ANCOM-BC, or ANCOM-BC2).

As for your questions:

## Question 1

> One thing I still don't understand is why are structural zeros a problem? Let's say we have 2 groups, and one them has Taxon A in 15 samples, and one of them has Taxon A in 0 samples, isn't this a strong indicator that there are differences between these groups for Taxon A

structural zeros are not a problem. The tricky part is that the detection of structural zeros is based on a separate paper [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/), so detecting structural zeros is independent of ANCOM, ANCOM-BC, or ANCOM-BC2 methodologies. The example you listed here is a perfect one for a taxon with structural zeros, and it will be declared as differentially abundant. That's why you will see more significant taxa when turning `struc_zero = TRUE`. It is because taxa with structural zeros are also considered significant. Also, setting `neg_lb = TRUE` will make the detection of structural zeros more liberal (you will identify more taxa with structural zeros).

## Question 2

> Why are there different results depending on whether you do ANCOM-BC or ANCOM

So here are 3 combinations for detecting structural zeros: 1) option 1: `struc_zero = FALSE` (regardless `neg_lb = TRUE` or `neg_lb = FALSE`), 2) option 2: `struc_zero = TRUE, neg_lb = FALSE` or 3) option 3: `struc_zero = TRUE, neg_lb = TRUE`. Order by conservative: option 1 > option 2 > option 3, which means option 1 will give you the least number of significant taxa (since no structural zeros will be detected), and option 3 will give you the most.

## Question 3

> If all the significant differences come up with a W=Inf, would you exclude these results

`W = Inf` means it is a taxon with structural zeros, and it will be considered significant. I wouldn't exclude these results but keep in mind that the significance of these taxa is not determined by ANCOM (or ANCOM-BC, ANCOM-BC2) but by the presence-absence test. Usually, if the sample size is limited and you have very sparse data (e.g., at the species level), most significant results are likely coming from structural zeros. Agglomerating data to higher taxonomic levels usually helps.

## Question 4

> How can you create a volcano plot for findings with W=Inf

Again, we recommend separate discussions on taxa with structural zeros and taxa without structural zeros. Taxa with structural zeros do not have W statistics or p-values since they are not based on ANCOM, ANCOM-BC, or ANCOM-BC2 methodologies. Making a separate bar graph of their relative abundances could be a visualization option (you will see some bars of zero lengths while others have some values).

## Question 5

> What does a SE=0 mean if ANCOM-BC considers taxon to be significantly abundant practically

These taxa with SE = 0 mean they contain structural zeros. SE = 0 are manually made simply because they do not go through the ANCOM-BC process, but I merge them to the `ancombc` results altogether. I realize it causes confusion to users, so in `ancombc2` function, taxa with structural zeros are completely removed from the ANCOM-BC2 process and are summarized in a separate table.

## Question 6

> Can you access clr mean differences in ANCOM-BC and the updated ANCOM

Yes. For `ancombc`, you can created the bias-corrected abundances table (see section 4.3 of the [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html#ancombc-primary-result)) and then calculate the clr differences manually. As for `ancom`, since there is no bias-corrected abundance table, you can construct the clr transformed table either from the raw count table or importing from the `ancombc` output. For an example of computing clr mean differences, you can see this [code trunck](https://github.com/FrederickHuangLin/ANCOM-Code-Archive/blob/master/programs/ancom.R#L265). I decided to remove the volcano plot comparing clr mean difference and the W statistics from `ancom` output because the author (Dr. Shyamal Das Peddada) believes the results are misleading since ANCOM is based on ALR transformation not CLR. We chose to plot the W statistics only.

## Question 7

> In general should I worry of I have many 0s for W-statistics (e.g. 206/300)

No. In means these taxa are completely null taxa as considered by `ancom`

Hope you find my responses helpful.

These are all great questions! Please do not hesitate to let me know how can I make the document clearer.

Best,
Frederick

**Comment by microb123** [comment]
Hi Frederick,

I have two group “HFD” and “Regular chow”.  Taxa f__Selenomonadaceae and f__Saccharimonadaceae is only present in “HFD” group and taxa f_Coriobacteriales_Incertae_Sedis in “Regular chow” group but when I ran the following ancombc 

out = ancombc(phyloseq = family_data, formula = "Group",
              p_adj_method = "fdr", prv_cut = 0.1, lib_cut = 0, 
              group = "Group", struc_zero = TRUE, neg_lb = FALSE, tol = 1e-5, 
              max_iter = 100, conserve = TRUE, alpha = 0.05, global = FALSE) 

I got positive lfc value for f__Selenomonadaceae and f__Saccharimonadaceae. How it is possible to have positive lfc when there is no read present in that group?

<img width="1235" alt="Screenshot 2022-11-17 at 1 21 48 PM" src="https://user-images.githubusercontent.com/104597614/202543505-ba44c0d7-5bc7-4fc6-9aad-41a739e9cf32.png">

I read couple of thread regarding structural zero and how they are handle by ANCOMBC, but couldn't understand why I got positive lfc for all three taxa when pattern of presence of structural zero between the group is different. 

Also, just to be sure, the output of this ancombc formula is " differentially abundant taxa in regular chow group compare to HFD",  right?

**Comment by FrederickHuangLin** [comment]
Hi @microb123,

As for your question

> I got positive lfc value for f__Selenomonadaceae and f__Saccharimonadaceae. How it is possible to have positive lfc when there is no read present in that group?

The reason why you saw positive lfc when the corresponding taxon is not even present in that group is that ANCOM-BC is working on bias-corrected abundances, not raw abundances. Thus, there is a chance that after correcting for sampling fractions, there are positive counts in that group. 

I am aware this could be confusing for users, so in `ancombc2`, the results of structural zeros will not be incorporated into the ANCOM-BC workflow but given in a separate table.

Hope it helps!

Frederick

**Comment by microb123** [comment]
Thank you Dr. Frederick for the explanation. It helped.

And thank you for ANCOMBC package and continue improving it.
