### ISSUE TITLE
comparing ACCOMBC and other tools

### ISSUE THREAD

**Issue by MjelleLab** [FrederickHuangLin/ANCOMBC#103]
I have detected a species (SpeciesX) that is differentially abundant in three other tools (maaslin2, zicoseq and metagenomseq). 
In ANCOMBC it gets a q-values of 1. A simple t-test on the counts does indeed show that its significantly abundant. 
Any idea why its not detected by ANCOMBC? My data has a lot of zeros. 
In group1 its detected in 9 out of 16 samples. In group 2 its detected in 20 out of 205 samples. 

`ancombc2(data = carbom,struc_zero = T,fix_formula = "tumor", group="tumor",prv_cut = 0,lib_cut = 0)
`

```
             lfc_(Intercept) lfc_tumorOther se_(Intercept) se_tumorOther W_(Intercept) W_tumorOther p_(Intercept) p_tumorOther q_(Intercept)
SpeciesX     0.007913902                  -0.008290609      0.2166153                    0.2249107    0.03653437                 -0.03686179     0.9708563                   0.9705952             1
             q_tumorOther diff_(Intercept) diff_tumorOther
SpeciesX                           1            FALSE                          FALSE

```
```

test <- as.data.frame(cbind(t(counts[grep("SpeciesX",rownames(counts)),]), data$tumor))
test1 <- test[grep("Other", test$V2),]
mean(as.numeric(test1$SpeciesX))
[1] 0.08762795
test2 <- test[grep("Other", test$V2, invert = T),]
mean(as.numeric(test2$SpeciesX))
[1] 0.7923181



```
> table(test1$SpeciesX >0)

FALSE  TRUE 
  185    20 
> table(test2$SpeciesX >0)

FALSE  TRUE 
    7     9 
```


t.test(as.numeric(test1$SpeciesX),as.numeric(test2$SpeciesX))



	Welch Two Sample t-test

data:  as.numeric(test1$SpeciesX) and as.numeric(test2$SpeciesX)
t = -2.4351, df = 15.487, p-value = 0.0274
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.31982378 -0.08955657
sample estimates:
 mean of x  mean of y 
0.08762795 0.79231812 
```

**Comment by FrederickHuangLin** [comment]
Hi @MjelleLab,

Generally, different methods are based on different assumptions, so there is no guarantee that a taxon can be detected by all of them. A key difference between ANCOM-BC2 (as well as ANCOM-BC) and t-test is that ANCOM-BC2 is working on bias-corrected data. You will get a more similar result if you apply t-test on bias-corrected data as well.

Here are a few suggestions to better dig into the result:

- Provide a Venn diagram comparing the significant taxa identified by these DA methods. Based on what I learned, usually, ANCOM-BC (ANCOM-BC2) and maaslin2 have a large number of overlap in significant taxa, while metagenomeSeq has the largest number of significant taxa (this method is more liberal). These overlapped taxa are likely more robust.
- Set `pseudo_sens = TRUE` and check the sensitivity table for pseudo-count addition (`pseudo_sens_tab`). There is a possibility that the significance of Species X is solely due to the addition of a pseudo-count.

Best,
Huang
