### ISSUE TITLE
Can one retrieve a normalized/bias corrected count table from ancombc2 results?

### ISSUE THREAD

**Issue by LLansing** [FrederickHuangLin/ANCOMBC#115]
Can one retrieve a normalized/bias corrected count table from ancombc2 results? I am interested in having the transformed taxa counts.

Does ancombc2 transform the count tables or does it only produce separate values that are measurements of the biases?
If ancombc2 does not provide this sort of table, is there a logical way of producing one using the bias measurement values?

**Comment by FrederickHuangLin** [comment]
Hi @LLansing,

You can check the section named "Bias-corrected abundances" in this [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html).

Please note that we are only able to estimate sampling fractions up to an additive constant. Thus, only the differences between bias-corrected abundances are meaningful, not absolute values.

Best,
Huang

**Comment by LLansing** [comment]
@FrederickHuangLin , thank you.
I see in the vignette that the sampling fraction bias is taken into account. Is there a similar way to include the _taxon-specific (sequencing efficiency) biases_ described as a new addition to [ANCOMBC2](https://bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html)?

**Comment by FrederickHuangLin** [comment]
Hi @LLansing,

We assume that taxon-specific biases vary across taxa, but they remain the **same** across samples in one taxon. Thus, you can derive the bias-corrected abundances using `ancombc2` in the same fashion as shown in `ancombc` tutorial.

Similar to `ancombc`, only the difference between bias-corrected abundances **within one taxon** are meaningful. Since the taxon-specific biases are not estimable, the difference between bias-corrected abundances **across different taxa** are NOT meaningful.

For instance, given the following bias-corrected abundance table

```
                sample A        sample B
OTU1           10                  100
OTU2           50                  200
```

You can say that the difference between sample A and sample B in OTU1 is 90, or the difference between sample A and sample B in OTU2 is 150, but it is not correct to say the difference between OTU1 and OTU2 in sample A is 40.

Best,
Huang
