### ISSUE TITLE
Fold change interpretation

### ISSUE THREAD

**Issue by estebannieto93** [FrederickHuangLin/ANCOMBC#129]
Dear Frederick,

I have run ANCOM-BCII, and I have a question about the interpretation of lfc. The lfc between the two groups behaves in the opposite way I expected according to the abundance of these taxa. For example, I have 2 groups; in group A, taxon 1 has an abundance of 1052, 2317, and 1445. In group B,  taxon 1 has an abundance of 6550, 4093, and 2866. But the lfc A_B is 2,80. Why does that happen, if the abundance in A is lower than in B? I know that the lfc is not calculated directly from the abundance, but should it not reflect the same behavior observed in the abundance?

**Comment by FrederickHuangLin** [comment]
Hi @estebannieto93,

The reason is that ANCOM-BC2 or ANCOM-BC is not working on the observed abundances but bias-corrected abundances. Could you calculate the bias-corrected abundances following the tutorial [here](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html) (there is a section called "Bias-corrected abundances") and see if you can get LFC between A and B for approximately 2.80?

Best,
Frederick
