### ISSUE TITLE
Error: 'rank' must be a value from 'taxonomyRanks()'

### ISSUE THREAD

**Issue by wn835166087** [FrederickHuangLin/ANCOMBC#143]
Hi there,
I built an SummarizedExperiment data from individual datasets, and i tried to use the below codes but I got errors
`
out = ancombc(data = se, assay_name = "counts", 
              tax_level = "Family", phyloseq = NULL, 
              formula = "if_CN,if_CY,HABs", 
              p_adj_method = "holm", prv_cut = 0.10, lib_cut = 1000, 
              group = "MC_chlA", struc_zero = TRUE, neg_lb = TRUE, tol = 1e-5, 
              max_iter = 100, conserve = TRUE, alpha = 0.05, global = TRUE,
              n_cl = 1, verbose = TRUE)
`

`
Error: 'rank' must be a value from 'taxonomyRanks()'
`

not sure why does it happen. Any help will be appreciated!
Best,
Nan

**Comment by antagomir** [comment]
What says `taxonomyRanks(se)`?

Is it possible to have fully reproducible example for troubleshooting?

**Comment by eepackard** [comment]
Hi @wn835166087 

I also had this issue. To resolve it, I had to fix the rank names in my phyloseq taxonomy file from "ta1", "ta2", "ta3", etc. to "Kingdom", "Phylum", "Class", etc. This happens when forming a tax_table in phyloseq from a dataframe instead of a matrix. Even though rank names and the tax_level I call for matched (ex. rank name in phyloseq is "ta6" and in the ancombc2 function tax_level = "ta6") it had to be "Kingdom", "Phylum" "Class", "Order", "Family" "Genus" or "Species".
