### ISSUE TITLE
ancombc2 - No variable named X in the reference grid

### ISSUE THREAD

**Issue by carmennns2** [FrederickHuangLin/ANCOMBC#162]
Hi, 

I have previously been using ancombc, however, decided to try ancombc2 for longitudinal analysis. 

I keep getting this error: "No variable named X in the reference grid", despite me clearly seeing it in my phyloseq sample data. 

I wonder if this is a problem due to my small sample size. I only have a total of 20 samples (10 samples at two timepoints. Of the 10 different samples, they came from 4 different people). I want to compare the first timepoint to the second timepoint for each of the 10 samples, and see if there are any differentially abundant species overall. 

My variables are:
Time (numerical, in months)
Individual (factor of 4 levels, the donor ID)
Donation (factor of 10 levels, the donation number (as each donor can provide multiple donations))

The code I have been using is:
ancombc2(
  data = physeq, fix_formula = Time, rand_formula =  (1 individual/donation), tax_level = "Genus", 
  p_adj_method = "BH", prv_cut = 0, lib_cut = 0, n_cl = 5, pairwise = TRUE, 
  group = "Donation", struc_zero = FALSE, neg_lb = FALSE, alpha = 0.05, global = TRUE, verbose = TRUE)

Do you how I can resolve this error?

Thank you so much!(:
 Carmen

**Comment by FrederickHuangLin** [comment]
Hi @carmennns2,

I have reviewed the syntax you provided and have noticed several issues that may be causing problems.

Firstly, it is important to specify the quotation marks for both the `fix_formula` and `random_formula`. For example, instead of `fix_formula = Time`, it should be written as `fix_formula = "Time"`.

Secondly, the `rand_formula` appears to be incorrect. If you want to specify a random intercept and a random slope for `individual` within each level of `donation`, the correct syntax would be `rand_formula = "(1 + individual | donation)"`.

I hope these corrections are helpful. Please let me know if you have any further questions or concerns.

Best regards,
Huang
