### ISSUE TITLE
Error when species from different genera share an epithet: "Warning: non-unique values when setting 'row.names':"

### ISSUE THREAD

**Issue by FunGalMax** [FrederickHuangLin/ANCOMBC#164]
Hello, 

Love the package! It's been extremely helpful.

I've run into an issue with trying to run _ancombc2()_ on an ITS fungal dataset. I want to use the "Species" taxon level, but some of the species share an epithet despite being from different genera (e.g., _Fusarium acutatum_ and _Acremonium acutatum_). Is there an easy way to deal with this? 

Thanks,
Max Spencer

**Comment by FrederickHuangLin** [comment]
Hi @maxwspencer,

You can try to rename the species name with "genus + species." For instance, instead of using "acutatum," you can try renaming it by pasting the genus name to it as well, such as "F. acutatum" or "A. acutatum."

Also, I think if your input data is in `tse` format, it will take care of the duplicate name issue for you automatically. Perhaps @antagomir can provide more insights about it?

Thanks,
Huang

**Comment by antagomir** [comment]
This should work if data is in the _TreeSummarizedExperiment_ format.

```
library(mia) 

# Load demo data and rename the data with a more generic variable name
data(peerj13075, package="mia") 
tse <- peerj13075 

# Check the taxonomy table
rowData(tse)[, taxonomyRanks(tse)]

# Get the labels with rank info
taxa.names <- getTaxonomyLabels(tse, make_unique=TRUE)
print(head(taxa.names))

# Set new row names
rownames(tse) <- taxa.names

# Or provide new columns in rowData (Let's call it "Unique" here but can be anything)
rowData(tse)$Unique <- taxa.names
```

**Comment by FunGalMax** [comment]
Thank you both, this fixed the problem for me!
