### ISSUE TITLE
Repeated measures & using bias-adjusted counts elsewhere?

### ISSUE THREAD

**Issue by JCSzamosi** [FrederickHuangLin/ANCOMBC#17]
Hello,
You mention in your paper that it is possible to use ANCOMBC with repeated-measures designs. I was wondering if this had been implemented in ANCOMBC already (perhaps as support for random effects)?

If not, is it reasonable to run `ancombc()`, take the bias-adjusted counts, and use them in, say, `lme4::lmer()` to take advantage of random effects?

Thanks

**Comment by FrederickHuangLin** [comment]
Hi Huahui,

Thanks for your interest in using ANCOMBC!

The current version of ANCOMBC is only able to perform covariates adjustment and global tests as mentioned in the paper. The longitudinal analysis is currently not available, but we are drafting the paper about it. We will add the corresponding functions to the ANCOMBC package once the new paper gets published. Per your question, since the estimation of the bias term is closely related to the model your pre-specify, I am afraid it is not workable to implement `lme4::lmer()` in an ad-hoc way.

Stay tuned!
Huang

**Comment by nick-youngblut** [comment]
Just to be clear (from https://doi.org/10.1038/s41467-020-17041-7):

> By virtue of linear regression formulation, ANCOM-BC can be applied to a broad collection of study designs, including longitudinal data, repeated measurements design, covariance adjusted analysis, and so on

"repeated measurements design" is or is not possible with ANCOM-BC?

**Comment by FrederickHuangLin** [comment]
Hi @nick-youngblut,

Thanks for your question! The repeated measurements design is possible with ANCOM-BC methodology; however, the R packages has not yet updated this feature because of an unexpected delay.

Best,
Huang

**Comment by nick-youngblut** [comment]
I see. Thanks for the clarification and the good package! I especially like how it is available from both bioconductor and bioconda.

**Comment by FrederickHuangLin** [comment]
Hi @dpelegri,

We have put all the resources to develop the methodology for correlation analysis of microbiome data, and the paper will be published soon. Unfortunately, I am not able to give you a specific date when the ANCOM-BC longitudinal analysis is available, we are trying to wrap it up by early next year.

Huang
