### ISSUE TITLE
collapse taxa

### ISSUE THREAD

**Issue by GaryZhangYue** [FrederickHuangLin/ANCOMBC#192]
Hi Frederick,

I have a question regarding the taxa collapsing function in ANCOMBC. I noticed that ANCOMBC can now collapse taxa internally when the argument "tax_level" is given. This is nice since we no longer need to collapse it beforehand. However, when I look at the results, I see the taxonomic levels above the set tax_level are also included in the test. For example, when I set the tax_level = "Genus", while I saw the most of the entries in the results are Genus, Kingdom to Family levels are also included. Are those unclassified reads (e.g., Phylum:Proteobacteria would be the number of read of unclassified Proteobacteria)?

Best,
Gary

**Comment by FrederickHuangLin** [comment]
Hi Gary!

Yes, that is correct! `Phylum:Proteobacteria` are those that can only be annotated to the phylum level. 

Best,
Frederick

**Comment by microb123** [comment]
Hi, @GaryZhangYue are you able to figure out why other taxonomy levels are also included when you are just running at the genus level? I also have similar issues. Even though I was running ancombc2 at the "genus" level, there were couples of the family included.  I tried with both tse object and the phyloseq object but the issue is the same.  When I tried with  aggregate_taxa from the microbiome r package there weren't any families included but it gave different result 

<img width="736" alt="Screenshot 2024-08-13 at 12 58 25 AM" src="https://github.com/user-attachments/assets/5914c74a-8f5c-4dc7-a879-ae26c12194ba">

Also, @FrederickHuangLin  how can we extract full taxonomic classifications? I tried with tse object as suggested in #147 but it didn't work.
