### ISSUE TITLE
Difference between multiple pairwise comparisons and pattern analysis

### ISSUE THREAD

**Issue by luisebe** [FrederickHuangLin/ANCOMBC#193]
Hi Frederick, 

I have been trying out your ANCOM-BC2 package and want to congratulate you on this great microbial analysis tool!

I do have one question regarding interpretability of the various plots and analysis featured in your vignette. 

a) In the longitudinal ANCOM-BC2 function, do I understand correctly that the global test result returns any taxon which is differentially abundant across time in any of my groups? (kind of like an ANOVA?)
b) regarding the multiple pairwise comparisons, is it correct to assume these are the longitudinal fold changes per group in relation to the reference group, irrespective of the other intervention groups? (kind of like 3 independent paired t-tests?) How is this different compared to the primary result, which also features lfc values for the diet (in a model with formula = "Time + diets")? 
c) How can I then interpret the output of the pattern analysis? Is it the differences in longitudinal log fold changes per group, compared to the reference group? 
d) in your [ANCOM-BC2 vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC2.html) you plot tile plots featuring the BMI groups for both the primary results, global results and the pairwise results. What is the exact difference in the interpretation of these 3 tile plots?  Could you give me a brief example on when which ancombc2 output is best used? 

Thank you very much in advance for your help!

Best, 
Luise

**Comment by FrederickHuangLin** [comment]
Hello @luisebe,

Thank you for your inquiry, and I apologize for the delay in my response.

Here are my responses to your questions:

(a) Yes, conceptually, the global test is quite similar to ANOVA.

(b) The pairwise test is more potent compared to conducting separate two-group comparisons. This is because it pools information from all groups to perform bias correction. Let's say you have a `group` variable with three levels, namely, `A`, `B`, and `C`. The pairwise test will provide results for `A vs. B`, `A vs. C`, and `B vs. C`, whereas the primary results will only show `B vs. A` and `C vs. A` if `A` is the reference group.

(c) Pattern analysis is akin to a trend test. It evaluates hypotheses like `A > B > C`, which cannot be directly examined through pairwise comparisons.

(d) These three tests serve distinct purposes. The primary results exclusively compare against the reference group and do not correct for multiple comparisons between groups (although they do account for multiple testing across taxa). The global test is analogous to ANOVA, while the pairwise test encompasses all possible pairwise comparisons, effectively handling multiple comparisons and multiple testing. The choice of which test to employ largely hinges on your specific research questions.

Best regards,
Huang

**Comment by luisebe** [comment]
Dear Huang, 

thank you very much for this clarification, this helped a great deal!

Best, 
Luise
