### ISSUE TITLE
Curiosity: Is there a minimum number of samples that is recommended?

### ISSUE THREAD

**Issue by gabrielet** [FrederickHuangLin/ANCOMBC#209]
I have a dataset which seems to be very problematic. I think the problems are related to either the number of samples, i.e. 32, or the model i am trying to use which includes two fixed and one random effects or both. Of course if i apply (relatively) complex models the samples are subsetted and the more effects, the less samples i have for the _comparisons_. 

I tried many possibilities, e.g.:

```
fix_eff <- "Treatment*Timepoint" ; rand_eff <- "(1|Site)"

fix_eff <- "Treatment+Timepoint" ; rand_eff <- "(1|Site)"

fix_eff <- "Treatment ; rand_eff <- "(1|Site)"

fix_eff <- "TimePoint" ; rand_eff <- "(1|Site)"

fix_eff <- "Site+TimePoint+Treatment" ;
```

From what i can see, according to the many warnings i am observing, the complex the model the more samples are required. In particular it seems that random effects are the ones that are more problematic.

I was wondering, then, if there are some guidelines on an estimate of the number of samples that are _good enough_. I know it's not an easy question and it's highly dependent on the experimental design as well...but maybe someone has some suggestions.

EDIT:

i guess one possible solution would be to try other methods, as suggested in [this publication](https://doi.org/10.1038/s41467-022-28034-z).

**Comment by FrederickHuangLin** [comment]
Hi @gabrielet,

Yes, in statistics, it is generally true that more complex models require more data samples to be effectively trained or estimated. This principle is based on the fact that complex models have more parameters to estimate. To reliably estimate these parameters, more data points are required. Otherwise, there may not be enough information to distinguish between various parameter values, leading to high variance in the parameter estimates.

Unfortunately, there isn't a universal guideline for determining sample size in microbiome analysis. Some researchers start by using alpha diversity as an initial method for sample size estimation.

Best,
Huang
