### ISSUE TITLE
technical replicates

### ISSUE THREAD

**Issue by Midnighter** [FrederickHuangLin/ANCOMBC#21]
Hi again,

Many questions as a new user... Please let me know if you prefer to have e-mail conversations or you could enable the 'Discussion' feature for this repository; but issues are just fine for me.

I wonder how you suggest to handle technical replicates. As an example, I have multiple samples per patient in each group. In a linear mixed-effect model I could specify this as a random effect, e.g.,

```r
lme4::lmer(abundance ~ group + (1 | patient), ...)
```

One possible way is to combine abundance tables using mean values, I suppose, but that seems like a huge loss of information. Thank you for any insights.

**Comment by FrederickHuangLin** [comment]
Hi @Midnighter,

Thanks for your suggestion! The Discussions feature has been enabled!

Per your question, the current version of ANCOMBC is only able to perform covariates adjustment and global tests as mentioned in its paper. The mixed effects model is currently not available, the work has been delayed due to COVID-19 pandemic. We expect to add the corresponding functions to the ANCOMBC package by this year.

Meanwhile, I suggest using [ANCOM](https://github.com/FrederickHuangLin/ANCOM) for your study with repeated measures at this moment.

Best,
Huang

**Comment by Midnighter** [comment]
Great, thank you and good to know.

**Comment by jorondo1** [comment]
Hi, am I correct to assume that this has been adressed in the latest release, ANCOM-BC2?

**Comment by FrederickHuangLin** [comment]
Hi @jorondo1,

Yes! The current version of `ancom` and `ancombc2` support the mixed-effects models.

Please look for the latest version of `ANCOMBC` (devel version 2.1.1, release version 2.0.1 on Bioconductor 3.16, should be available after 2 business days), which has fixed some bugs regarding the mixed-effects models.

Let me know how it works!

Best,
Huang
