### ISSUE TITLE
Continuous variable as main variable of interest 

### ISSUE THREAD

**Issue by ChloePZS** [FrederickHuangLin/ANCOMBC#252]
Hello, 

I have used ANCOM-BC2 several times on categorical variables, but here I want to identify ASVs (16s) that significantly vary with a continuous variable (here the percent of settlement on tiles). 

In the package info (https://rdrr.io/github/FrederickHuangLin/ANCOMBC/f/README.md), I have read "For example, if you have a continuous variable like age as your main variable of interest, and you have additional categorical variables that need adjustment but are not directly related to your research question, you can include them in the formula while leaving group as NULL."

Yet, when I am trying this approach I have the following error : 

![image](https://github.com/FrederickHuangLin/ANCOMBC/assets/47737491/e6ef66f4-7a43-432e-b08b-272228e0d8d4)

Should I consider adding the categorical covariates as my group variable ? Is ANCOM-BC2 appropriate here ? 
Would another approach considering the continuous variable as the response variable instead of a predictor would be better ?

Many thanks for your help !

Best, 
Chloe

**Comment by vmaffei** [comment]
I saw this error (in an older version of ANCOMBC2) when I specified struct_zero = TRUE and left group as NULL. Setting struct_zero = FALSE or group = categorical_variable_of interest cleared the error for me. You might consider setting struct_zero = FALSE since your variable of interest is continuous. I believe the structural zero detection only applies to categorical variables.

**Comment by ChloePZS** [comment]
Great I'll try ! Thanks for your response
