### ISSUE TITLE
Variables 'change' after using ANCOMBC function

### ISSUE THREAD

**Issue by icaedi** [FrederickHuangLin/ANCOMBC#28]
Hello dr Lin,

I am very interested in using ANCOMBC to analyse a human microbiome dataset.
Unfortunately, I am running into a problem using the ANCOMBC function. 

I am not an experienced R user but I'll try to explain as best as I can.

e.g.: the variable “City” consisting of “Bur”, “Man”, “Kna”, “Tow”. 
After running ancombc, the columns of the output tables are headed: CityMan, CityKna, CityTow. 
The variable Bur has disappeared altogether. This happens for all the variables; the column name of the variable seems to replace one of the variables. 
In the merged phyloseq file used for ancombc this doesn’t seem to be an issue:
sam_data	list[40x5](phyloseq::sampledata) A data.frame with 40 rows and 5 columns
Town		factor				Factor with 4 levels: “Bur”, “Man”, “Kna”, “Tow”

I am sure I am missing something here and hopefully you can help.
Thank you very much in advance.
Regards, Ica

**Comment by FrederickHuangLin** [comment]
Hi @icaedi,

Thanks for your question! The phenomenon you have seen is basically due to the setting of a reference level in categorical variables.

For example, in your "City" variable, you have four levels which are “Bur”, “Man”, “Kna”, “Tow”. These levels are ordered alphabetically in R, by default, and the first level will be used as the reference level. So the effect size you see, such as `CityMan` is actually `CityMan - CityBur`, so are `CityKna` and `CityTow` (which are `CityKna - CityBur` and `CityTow - CityBur`, respectively).

For more information about changing the reference level, you can see this [post](https://stackoverflow.com/questions/3872070/how-to-force-r-to-use-a-specified-factor-level-as-reference-in-a-regression).

Best,
Huang
