### ISSUE TITLE
ANCOM v2.1 and ANCOMBC, difference?

### ISSUE THREAD

**Issue by Ivy-ops** [FrederickHuangLin/ANCOMBC#5]
Hi developer, 
I am a little confused, what's the difference between ANCOM-BC and ANCOM v2.1?
I have been always using ANCOM v2.1, is it different from ANCOM-BC? 

Thanks!!!!

**Comment by FrederickHuangLin** [comment]
Hi @Ivy-ops,

Thanks for your interest in our methods!

Both ANCOM and ANCOM-BC are methods of differential abundance (DA) analysis and they are handling the same problem, which is to detect the differential abundant taxa. However, since these two methods are based on different methodologies, you will expect slightly different results from them using the same dataset. Based on our simulations, the results shall be pretty consistent.

Additionally, ANCOM-BC is still an ongoing project, the current ANCOMBC R package only supports testing for covariates and global test. Other tests such as directional test or longitudinal analysis will be available for the next release of the ANCOMBC package.

Best,

Huang

**Comment by joshborin** [comment]
Hi @FrederickHuangLin, I am wondering if ANCOM-BC is now able to do longitudinal analyses? I did not see it mentioned in documentation, just cross-sectional analysis.

Thanks!
Josh

**Comment by FrederickHuangLin** [comment]
Hi @joshborin,

Thanks for your inquiry!

`ancombc` does not support the longitudinal analysis in this version (1.6.2), but it is undergoing a major update that will incorporate longitudinal analysis and more. The update will be published in probably a month.

Best,
Huang
