### ISSUE TITLE
What to do with the group argument when your predictors are all continuous

### ISSUE THREAD

**Issue by JCSzamosi** [FrederickHuangLin/ANCOMBC#52]
Hello,

I apologize if this has been answered elsewhere, but it's not clear to me what I should do with the `group =` argument when all of my predictors are continuous. I would like to control for structural zeros if possible, but I don't think I can give a continuous variable to the `group` argument and I don't have any categorical predictors in my model.

Thanks!

**Comment by FrederickHuangLin** [comment]
Hi @JCSzamosi,

If all of your variables are continuous, then you do not have to specify the `group` argument since the structural zeros make sense only when there is a categorical variable for grouping. 

If you are really interested in the structural zero output (for exploratory purposes), you can try to categorize one of your continuous variables (e.g. dichotomized the variable) and put it into the `group` argument.

Best,
Huang
