### ISSUE TITLE
ANCOM-BC global test and multiple comparisons

### ISSUE THREAD

**Issue by tenguzame** [FrederickHuangLin/ANCOMBC#56]
Dear all,
First of all, thanks for developing such a tool, it is proving very helpful in many of my current studies.
I have a couple of questions regarding its utilization in one of my recent study designs. I have a batch of samples with varying feature abundances; I have identified a total of 6 groups (C1 to C6) and I'd like to identify differentially abundant features across the dataset using ANCOM-BC. However, the test itself relies on comparisons against a reference, which I don't have. To avoid resorting to manually performing a batch of multiple comparisons each time defining a different group as a reference, I tried to do the following:

1) have ANCOM-BC define globally differentially-abundant features through the global test;
2) recover the identified features from a CLR-normalized table and plot their abundances by group.

I am however unsure about this. What does really the global test procedure do? Should I normalize the results by subtracting the sampling fraction from log-normalized feature abundances as the vignette shows?
Thanks for the advices!
Best regards

**Comment by FrederickHuangLin** [comment]
Hi @tenguzame,

Thanks for your inquiry!

As for your questions, the ANCOM-BC global test aims to identify taxa that are (significantly) differentially abundant in at least one group (if there are multiple groups). Therefore, no reference group is needed.

You do not have to normalize the count table before doing any differential abundance analysis using ANCOM-BC, since the normalization (or we called it bias-correction) step is embedded in the ANCOM-BC procedure). 

Visualization using CLR-normalized data is a great idea! Since CLR transformation is compositionally robust, there is no need to normalize data either.

Best,
Huang
