### ISSUE TITLE
Diff_abn for first variable depends on the second variable reference level - expected? 

### ISSUE THREAD

**Issue by mverce** [FrederickHuangLin/ANCOMBC#58]
Dear Frederick,

I have been happily using ANCOM-BC for a while and plan to keep using it in the future. However, something is puzzling me now that I'm working on a data set with two variables, of which the variable Status has 2 levels and the variable Treatment has 3 levels.

I ran ancombc with the formula "Status*Treatment". This gave me two of the three possible comparisons for Treatment, but the third comparison for the variable Treatment is also relevant in this case, so I repeated ancombc with the same formula but with the Treatment levels switched around so that another level was the reference, which achieved the goal.

However, I noticed that the 79 ASVs that were differentially abundant between Status levels in the first comparison only partially overlapped the 18 ASVs that were differentially abundant between Status level in the second comparison (5 ASVs in common). I switched around or omitted Treatment factor levels some more and saw that the ASVs differentially abundant between the Status levels depended heavily on which Treatment factor level was the reference.

Did I make a mistake somewhere? Is this expected behaviour and the comparison for the first factor have to be repeated with every level of the second one as reference (and vice versa)? Do you have any suggestions on how to proceed in cases like this and how to interpret these results? I would be grateful for any comment or advice!

With kind regards,
Marko

**Comment by FrederickHuangLin** [comment]
Hi @mverce,

This is a great question! Actually, the results you observed are not limited to ANCOMBC but applied to general regression models. 

Consider the following example:
```
dat = read.csv("https://stats.idre.ucla.edu/wp-content/uploads/2019/03/exercise.csv")
dat$prog = factor(dat$prog,labels = c("jog", "swim", "read"))
dat$gender = factor(dat$gender,labels = c("male", "female"))

dat$prog = factor(dat$prog, levels = c("jog", "swim", "read"))
fit1 = lm(loss ~ prog*gender, data = dat)
summary(fit1)

dat$prog = factor(dat$prog, levels = c("swim", "read", "jog"))
fit2 = lm(loss ~ prog*gender, data = dat)
summary(fit2)
```

What you are interested in is the marginal effect of "gender", while you have another covariate "prog" and would also like to consider the interaction term of "gender * prog" as well. In the first model, you set "jog" as the reference level, but in the second model the reference level was switched to "swim". However, if you print the results for both models, the coefficients for "gender" seem different.

Model 1 gives:
```
Coefficients:
                      Estimate Std. Error t value Pr(>|t|)    
(Intercept)            11.7720     0.5322  22.118  < 2e-16 ***
progswim               10.7504     0.7527  14.282  < 2e-16 ***
progread              -15.7276     0.7527 -20.895  < 2e-16 ***
genderfemale           -7.4833     0.7527  -9.942  < 2e-16 ***
progswim:genderfemale  14.0787     1.0645  13.226  < 2e-16 ***
progread:genderfemale   7.8188     1.0645   7.345 4.63e-13 ***
```

Model 2 gives:
```
Coefficients:
                      Estimate Std. Error t value Pr(>|t|)    
(Intercept)            22.5224     0.5322  42.316  < 2e-16 ***
progread              -26.4780     0.7527 -35.177  < 2e-16 ***
progjog               -10.7504     0.7527 -14.282  < 2e-16 ***
genderfemale            6.5953     0.7527   8.762  < 2e-16 ***
progread:genderfemale  -6.2599     1.0645  -5.881 5.77e-09 ***
progjog:genderfemale  -14.0787     1.0645 -13.226  < 2e-16 ***
```

You will see the coefficients for `genderfemale` are -7.4833 and 6.5953, respectively. So why is the difference? It is because the interpretations are different when you change the reference level for another covariate.

The coefficient of `genderfemale = -7.4833` in the first model refers to the effect size of **female and jog**; on the contrary, The coefficient of `genderfemale = 6.5953` in the second model refers to the effect size of **female and swim**. If you are interested in recovering the effect size of **female and jog** in the second model, you can calculate it by `genderfemale + progjog:genderfemale`, which will give you -7.4833, the same as the first model.

Come back to ANCOMBC model, it means that changing the reference level of a covariate involved in the interaction of your main variable, will change the "marginal" effect of the main variable of interest since the reference is the combination of them, and it changes as well.

Hope it helps!

Best,
Huang

**Comment by mverce** [comment]
Hi @FrederickHuangLin,

Thank you very much for your reply! It seems I'll need to do some further reading and thinking to be sure I don't misinterpret any results when it comes to interactions in such cases, but your example and pointers will be a huge help in that!

Thanks a lot and best regards,
Marko
