### ISSUE TITLE
Does ANCOMBC supports only one variable of interest?

### ISSUE THREAD

**Issue by Ivy-ops** [FrederickHuangLin/ANCOMBC#6]
Hi developer,

Does ANCOMBC support only one continuous variable of interest? 
For example, in the vignettes:

> out = ancombc(phyloseq = phylum_data, formula = "age + nation + bmi_group", 
>               p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000, 
>               group = "nation", struc_zero = TRUE, neg_lb = TRUE, tol = 1e-5, 
>               max_iter = 100, conserve = TRUE, alpha = 0.05, global = TRUE)

Is that possible, if I want to test the association between age(only one continuous variable) and each taxa？
Appreciate it!

**Comment by FrederickHuangLin** [comment]
Hi @Ivy-ops,

If there is only one variable available in your dataset, say `age`, you can modify the code as 

`out = ancombc(phyloseq = phylum_data, formula = "age",
p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000,
group = NULL, struc_zero = FALSE, neg_lb = FALSE, tol = 1e-5,
max_iter = 100, conserve = TRUE, alpha = 0.05, global = FALSE)`.

However, if you think by only adjusting the `age` effect, your model is under-fitting, you can still incorporate other covariates by specifying the formula, say `formula = "age + nation + bmi_group"`, but focus on columns (e.g. beta values, Ws, p-values, etc.) related to `age` in `res` outputs. These columns will give your marginal effects between `age` and each taxon.

Best,

Huang

**Comment by Ivy-ops** [comment]
Hi @FrederickHuangLin ,
However, I always get the error as below, I am afraid of something wrong? Again, appreciate your time!

```
> out = ancombc(phyloseq = phylum_data, formula = "age", 
> +               p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000, 
> +               group = "age", struc_zero = TRUE, neg_lb = TRUE, tol = 1e-5, 
> +               max_iter = 100, conserve = TRUE, alpha = 0.05, global = TRUE)
> Error in beta_hat_sub[i, ] : incorrect number of dimensions

```

**Comment by FrederickHuangLin** [comment]
Hi @Ivy-ops,

I guess the `age` effect is continuous, which means specifying `group = "age"` is not appropriate since the `group` argument would expect input of a categorical variable.

The following codes should work:
`out = ancombc(phyloseq = phylum_data, formula = "age", 
              p_adj_method = "holm", zero_cut = 0.90, lib_cut = 1000, 
              group = NULL, struc_zero = FALSE, neg_lb = FALSE, tol = 1e-5, 
              max_iter = 100, conserve = TRUE, alpha = 0.05, global = FALSE)`

Best,

Huang

**Comment by Ivy-ops** [comment]
@FrederickHuangLin , Yes, it works!! Thanks!!!

**Comment by MjelleLab** [comment]
@FrederickHuangLin 

Hi @FrederickHuangLin In my res-object I get one column for each birthYear (1970, 1980 etc) instead if just one column with all the birthYears (age), like in tour tutorial. Is this because my birthYear variable is not a factor? Does it affect the results? It takes a long time to run, probably because its testing each birthYear. Any suggestion?

out = ancombc(phyloseq = carbom, formula = "Tumor + birthYear + gender", group="Tumor",prv_cut = 0,lib_cut = 0)

**Comment by FrederickHuangLin** [comment]
Hi @MjelleLab,

The reason is probably that your `birthYear` column is a `factor` or a `character` rather than a `numeric`. You can try

```
metadata$birthYear = as.numeric(metadata$birthYear)
```

to transfer the data type.

Also, I am happy to inform you that the new `ANCOMBC` package has been released. It contains `ancombc2` function, which is fully evolved from `ancombc`. 

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the devel version is ready here!).

Best,
Huang
