### ISSUE TITLE
Group variables and global test results

### ISSUE THREAD

**Issue by archiesachdeva** [FrederickHuangLin/ANCOMBC#61]
Dear ANCOMBC developer,

I am trying to run ANCOMBC with 5 confounders and 1 group variable with 2 levels as follows

fit.ancombc0 = ancombc(phyloseq = phydata, formula = "x1 +x2+x3+x4+x5+ group" , 
                       p_adj_method = "BH", zero_cut = 0.90, lib_cut = 1000,
                       struc_zero = TRUE, neg_lb = FALSE,
                       tol = 1e-5, max_iter = 100, conserve = TRUE,
                       group = group, alpha = 0.05, global = TRUE)

I get the following warning message and my res_global output is NULL

Warning message:
In data_prep(phyloseq, group, zero_cut, lib_cut, global = global) :
  The multi-group comparison will be deactivated as the group variable has < 3 categories.

I am interested to find the Differentially abundant (DA) taxa between the two levels of my group variable. Does the above warning mean that ANCOMBC cannot provide DA taxa between two groups?

**Comment by ctipton4** [comment]
Not affiliated with the devs, but I might see an issue in your code. Try to rerun with `group = "group"`

**Comment by FrederickHuangLin** [comment]
Hi @archiesachdeva and @ctipton4,

Thanks for your interest in using ANCOMBC.

The warning message `The multi-group comparison will be deactivated as the group variable has < 3 categories.` indicates that your group variable `group` has less than 3 levels.

You can verify it by checking 
```
nlevels(meta(phydata)$group)
```

Since ANCOMBC global test is only meaningful when you have >= 3 levels (the alternative hypothesis is that there is **at least** one group that is differentially abundant across all groups), the global test function will be deactivated in your case. You can still check the effect of `group` in the primary output `fit.ancombc0$res`.

Best,
Huang

**Comment by archiesachdeva** [comment]
Thank you, @FrederickHuangLin for the clarification. I just wanted to be sure if I am using the package results correctly.
