### ISSUE TITLE
Error message after adjusting formula

### ISSUE THREAD

**Issue by jonathho** [FrederickHuangLin/ANCOMBC#65]
Hello,

Thank you for developing and sharing the ancombc package.

I have been running ancombc on a dataset using 2 covariates in the formula argument and it seems to be working great.
However, when I try to add a third covariate, I receive the following error message;
```
Error in vapply(seq(n_taxa), function(i) dnorm(Delta[i], delta, sqrt(nu0[i])),  : 
  values must be length 1,
 but FUN(X[[2]]) result is length 0
In addition: Warning messages:
1: In min(Delta, na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
2: In max(Delta, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
```
Would you happen to have any advice on where this is coming from and how to remedy it?

Thank you!

**Comment by FrederickHuangLin** [comment]
Hi @jonathho,

Thanks for your question!

To my best knowledge, the problem is likely coming from your third covariate! It is probably because 1) the third covariate contains a lot of missing values 2) the third covariate is highly correlated with the first two covariates which makes the corresponding coefficient matrix singular.

May you please check if you have either of these problems?

Best,
Huang

**Comment by jonathho** [comment]
Hi @FrederickHuangLin,

Yes, the third covariate is highly correlated with the second, meaning it does not add much to the model. This makes sense now.

Thank you so much!

Cheers!
