### ISSUE TITLE
input ASV table

### ISSUE THREAD

**Issue by GaryZhangYue** [FrederickHuangLin/ANCOMBC#66]
Hi Frederick,

What a great software to analyze differential abundance! 
I just have a brief question regarding the input ASV table. I noticed that you stressed multiple times that the input should be an absolute count table instead of a relative abundance table. I am wondering if you would recommend using a rarefied table as input or just raw data? 

Thank you!

**Comment by FrederickHuangLin** [comment]
Hi @GaryZhangYue,

That's a great question! Technically, you can use the rarefied table since it is still a count table; however, doing the rarefication introduces additional (unnecessary) randomness to the data, and sometimes it reduces the sample size as well (if samples with small library sizes were removed). Therefore, in general, I would recommend using the raw data rather than the rarefied data.

Best,
Frederick

**Comment by GaryZhangYue** [comment]
Hi @FrederickHuangLin, 

Thank you so much for your prompt reply. I will keep that in mind. 

Best
Gary
