### ISSUE TITLE
Adjustment p-value

### ISSUE THREAD

**Issue by andrebolerbarros** [FrederickHuangLin/ANCOMBC#76]
First of all, let me thank you for the amazing package, already "playing" with my data and `ancombc`.

One question that came up to me recently: shouldn't the default method for p-value correction be `fdr`? I think, from the "traditional" methods, it is the one indicated for multiple testing correction, while Holm should be for multiple comparisons.

Thanks in advance!

André

**Comment by FrederickHuangLin** [comment]
Hi @andrebolerbarros,

That is a great question! 

The reason why we recommend using `holm` instead of `fdr` (aka `BH`) is B-H procedure assumes that tests are independent or positively regression dependent, which might not be true due to complex underlying microbe-microbe interactions. Therefore, we tend to use a more conservative controlling procedure to prevent FDR inflation.

However, based on our simulation benchmarks, `BH` controlled FDR in most cases.

Best,
Huang

**Comment by andrebolerbarros** [comment]
That's a very relevant point, thanks for that! Maybe in compositional data, inherently B-H or fdr assumptions are not met and, thus, shouldn't be first choice!

**Comment by FrederickHuangLin** [comment]
I am aware there are new FDR controlling procedures that allow for various covariance patterns. We will keep an eye the availability of corresponding software.
