### ISSUE TITLE
Confused about using struc_zer/neg_lb options

### ISSUE THREAD

**Issue by Anto007** [FrederickHuangLin/ANCOMBC#82]
I have with me the results from DADA2 analysis of 16S rRNA amplicon data (total of 139000 ASVs) from 44 control and 43 treated libraries. When I ran the below on ANCOMBC v1.2.2, I got only **1 ASV** differentially abundant in the treated (Note- the % relative abundance of this ASV was zero in the control samples). I chose here "BH" as the `p_adj_method` so as to compare my results to that of DESeq2 (which by the way returned zero differentially abundant ASVs)
`ancombc(phyloseq=diff_count_physeq, formula="treatment", p_adj_method="BH", zero_cut=0.9, lib_cut=1000, group="treatment", struc_zero=TRUE, neg_lb=FALSE, tol=1e-05, max_iter=100, conserve=F, alpha=0.05, global=TRUE)`
When I change `struc_zero` as well as `neg_lb` to `TRUE`, I get **1450 ASVs** as being differentially abundant
When I change `struc_zero` as well as `neg_lb` to `FALSE`, I get **zero ASVs** as being differentially abundant
I went through your manual but I'm still confused as to which of these 3 results I should be considering as a valid result. I would highly appreciate any inputs here.

**Comment by FrederickHuangLin** [comment]
Hi @Anto007,

The detection of structural zeros is based on a separate paper [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/). More specifically, `neg_lb = TRUE` indicates you are using both criteria stated in section 3.2 of [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/) to detect structural zeros; Otherwise, `neg_lb = FALSE` will only use the equation 1 in section 3.2 of [ANCOM-II](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5682008/) for declaring structural zeros.

Therefore, setting `neg_lb = FALSE` is more conservative. Given the ASV table is usually very sparse, I tend to choose `neg_lb = FALSE` to prevent false discoveries. On the other hand, if you have a more dense table (e.g. family level table) with a sufficiently large sample size (Iike the sample size in your case), setting `neg_lb = TRUE` seems a better idea.

Best,
Huang

**Comment by Anto007** [comment]
Thank you so much for your kind response @FrederickHuangLin. I'm still a bit confused by your reply. The way I understood your response is that setting `neg_lb = TRUE` automatically means `struc_zero` is set to `TRUE`. Is my understanding correct here? If so, why do I see zero differentially abundant ASVs when I use `struc_zero=FALSE` and `neg_lb=TRUE` on my same dataset? The results are the same as when I set `struc_zero` as well as `neg_lb` to `FALSE`? I thought setting `struc_zero=FALSE` and `neg_lb=TRUE` on the dataset will yield 1450 ASVs as being differentially abundant i.e., the same result when I set `struc_zero` as well as `neg_lb` to `TRUE`

**Comment by Anto007** [comment]
Basically, I would like to know only one thing i.e, if setting `struc_zero=FALSE` and `neg_lb=TRUE` is ok for getting the most accurate DA results for my dataset? Thanks again!

**Comment by FrederickHuangLin** [comment]
Hi @Anto007,

Sorry for getting back to you late. `neg_lb` will have no function if you set `struc_zero = FALSE`. Thus, there are 3 possible combinations here: `struc_zero = FALSE` (regardless `neg_lb = TRUE` or `neg_lb = FALSE`), or `struc_zero = TRUE, neg_lb = FALSE` or `struc_zero = TRUE, neg_lb = TRUE`.

Best,
Huang

**Comment by Anto007** [comment]
ok

**Comment by FrederickHuangLin** [comment]
Hi @Anto007 ,

I am pleased to share with you that the major update for `ANCOMBC` package has been completed. Here are some highlighted new features:

- Add `ancombc2` function, which supports pairwise test and trend test for both cross-sectional and repeated measurements data
- Add sensitivity analysis for pseudo-count addition
- Fully support the `(Tree)SummarizedExperiment` class
- A more user-friendly output layout

Also, the documentation for structural zeros has been refined.

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the `devel` version is ready here!).

Best,
Huang
