### ISSUE TITLE
  attempt to set 'colnames' on an object with less than two dimensions

### ISSUE THREAD

**Issue by MjelleLab** [FrederickHuangLin/ANCOMBC#88]
Any idea what this error is? 

```


> carbom
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 445 taxa and 4948 samples ]
sample_data() Sample Data:       [ 4948 samples by 4 sample variables ]
tax_table()   Taxonomy Table:    [ 445 taxa by 2 taxonomic ranks ]


```
```
> out = ancombc(phyloseq = carbom, formula = "primaryTumorLocation + gender + birthYear", group = "primaryTumorLocation")
Error in `colnames<-`(`*tmp*`, value = covariates) : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning messages:
1: The multi-group comparison will be deactivated as the group variable has < 3 categories 
2: ANCOM-BC results would be unreliable when the number of taxa is too small (e.g. < 10)
The number of taxa in the current dataset is: 0 
```

**Comment by FrederickHuangLin** [comment]
Hi @MjelleLab,

Which version of `ANCOMBC` are you using? The error message `The number of taxa in the current dataset is: 0` showed that you have no taxa after filtering. You might want to modify the `prv_cut` and `lib_cut` arguments.

Best,
Huang

**Comment by TianyiChang** [comment]
Hello there

I got the same error using ANCOMBC 1.4.0 installed via Conda, with the example 'Build a Phyloseq-Class Object from Scratch' from the man page https://rdrr.io/bioc/ANCOMBC/man/ancombc.html

The problem was gone when using pre-built phyloseq object, e.g., data(GlobalPatterns)

I was wondering if you have identified what caused this problem.

Thanks

**Comment by FrederickHuangLin** [comment]
Hi @TianyiChang,

The reason why @MjelleLab got the above error is that there are 0 taxa after the filtering. 

Also, I am pleased to share with you that the major update for `ANCOMBC` package has been completed. Here are some highlighted new features:

- Add `ancombc2` function, which supports pairwise test and trend test for both cross-sectional and repeated measurements data
- Add sensitivity analysis for pseudo-count addition
- Fully support the `(Tree)SummarizedExperiment` class
- A more user-friendly output layout

Since we have switched the primary support data type to `(Tree)SummarizedExperiment` (`phyloseq` class is still supported), hopefully there will be no construction error as you encountered for creating a `phyloseq` object.

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the `devel` version is ready here!).

Best,
Huang
