### ISSUE TITLE
Specifying contrasts for results

### ISSUE THREAD

**Issue by JCSzamosi** [FrederickHuangLin/ANCOMBC#93]
When there are multiple predictor variables in model, possibly with interaction effects, it's not obvious to me which contrast is reported in the results table, or how to specify which contrast I would like the log fold change for. Is it possible to extract user-specified contrasts, like the `contrast=` argument does in DESeq2's `results()` function?

**Comment by FrederickHuangLin** [comment]
Hi @JCSzamosi,

Unfortunately, `ANCOMBC` does not support contrast in its current version. However, `ANCOMBC` package has just been updated to include `ancombc2` function, which supports pairwise test (with mdFDR control) and trend test for both cross-sectional and repeated measurements data.

Hope that partially solve your problem.

I just pushed the changes to the Bioconductor branches. It might take a few business days for the package to become available (but the `devel` version is ready here!).

Best,
Huang

**Comment by andreott** [comment]
Hi,
I have a related question. Assuming my group variable has three levels A, B and C but I am only interested in the contrasts A vs. B and A vs. C

So in ANCOMBC and ANCOMBC2, automatically, all three comparisons are performed automatically, right?

And in ANCOMBC, the adjusted p-values were computed separately for each contrast, while in ANCOMBC2, they are also taking into account the multiple comparisons?!

What would be the suggested strategy to solve my task? Subsetting the data and doing to separate runs for each contrast and afterwards joining the two p-value lists and re-adjust them on the merged list?
Besides the effect on the adjusted p-value computation, how would the analysis on the subsets instead of the full dataset effect the analysis?

Any hints are much appreciated! Thanks!

**Comment by FrederickHuangLin** [comment]
Hi @andreott,

Please find below my responses to your questions.

> So in ANCOMBC and ANCOMBC2, automatically, all three comparisons are performed automatically, right?

In `ancombc2`, you can specify `dunnet = TRUE` to turn on Dunnett’s type of test. If you make `A` the reference group, then only the comparisons `A vs. B` and `A vs. C` will be performed.

> And in ANCOMBC, the adjusted p-values were computed separately for each contrast, while in ANCOMBC2, they are also taking into account the multiple comparisons?!

Yes!

Hope that helps!

Best,
Huang
